language: python
python:
  - "3.7"

sudo: false

env:
  - TOXENV=py37-django22
  - TOXENV=py37-django30

matrix:
  fast_finish: true

install:
  - pip install tox virtualenv coveralls

script:
  - tox

after_script:
  - coveralls
